project_id = "ttoumiybdwcbzdujklfy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.gemini-chat]
verify_jwt = false

[functions.process-pdf]
verify_jwt = false

[functions.process-youtube]
verify_jwt = false